# Logistic Regression

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import OrderedDict

## Importing the dataset

In [ ]:
dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/50_Startups.csv')
X = dataset.iloc[:, 0:1].values
y = dataset.iloc[:,-1].values
print(X)


[[165349.2 ]
 [162597.7 ]
 [153441.51]
 [144372.41]
 [142107.34]
 [131876.9 ]
 [134615.46]
 [130298.13]
 [120542.52]
 [123334.88]
 [101913.08]
 [100671.96]
 [ 93863.75]
 [ 91992.39]
 [119943.24]
 [114523.61]
 [ 78013.11]
 [ 94657.16]
 [ 91749.16]
 [ 86419.7 ]
 [ 76253.86]
 [ 78389.47]
 [ 73994.56]
 [ 67532.53]
 [ 77044.01]
 [ 64664.71]
 [ 75328.87]
 [ 72107.6 ]
 [ 66051.52]
 [ 65605.48]
 [ 61994.48]
 [ 61136.38]
 [ 63408.86]
 [ 55493.95]
 [ 46426.07]
 [ 46014.02]
 [ 28663.76]
 [ 44069.95]
 [ 20229.59]
 [ 38558.51]
 [ 28754.33]
 [ 27892.92]
 [ 23640.93]
 [ 15505.73]
 [ 22177.74]
 [  1000.23]
 [  1315.46]
 [     0.  ]
 [   542.05]
 [     0.  ]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[ 46426.07]
 [ 91749.16]
 [130298.13]
 [119943.24]
 [  1000.23]
 [   542.05]
 [ 65605.48]
 [114523.61]
 [ 61994.48]
 [ 63408.86]
 [ 78013.11]
 [ 23640.93]
 [ 76253.86]
 [ 15505.73]
 [120542.52]
 [ 91992.39]
 [ 64664.71]
 [131876.9 ]
 [ 94657.16]
 [ 28754.33]
 [     0.  ]
 [162597.7 ]
 [ 93863.75]
 [ 44069.95]
 [ 77044.01]
 [134615.46]
 [ 67532.53]
 [ 28663.76]
 [ 78389.47]
 [ 86419.7 ]
 [123334.88]
 [ 38558.51]
 [  1315.46]
 [144372.41]
 [165349.2 ]
 [     0.  ]
 [ 22177.74]]


In [ ]:
print(y_train)

[ 96712.8  124266.9  155752.6  132602.65  64926.08  35673.41 101004.64
 129917.04  99937.59  97427.84 126992.93  71498.49 118474.03  69758.98
 152211.77 134307.35 107404.34 156991.12 125370.37  78239.91  14681.4
 191792.06 141585.52  89949.14 108552.04 156122.51 108733.99  90708.19
 111313.02 122776.86 149759.96  81005.76  49490.75 182901.99 192261.83
  42559.73  65200.33]


In [ ]:
print(X_test)

[[ 66051.52]
 [100671.96]
 [101913.08]
 [ 27892.92]
 [153441.51]
 [ 72107.6 ]
 [ 20229.59]
 [ 61136.38]
 [ 73994.56]
 [142107.34]
 [ 55493.95]
 [ 46014.02]
 [ 75328.87]]


In [ ]:
print(y_test)

[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94  96778.92  96479.51 105733.54]


## Feature Scaling (Write appropriate code for feature scaling)

In [ ]:
print(X_train)

[[ 46426.07]
 [ 91749.16]
 [130298.13]
 [119943.24]
 [  1000.23]
 [   542.05]
 [ 65605.48]
 [114523.61]
 [ 61994.48]
 [ 63408.86]
 [ 78013.11]
 [ 23640.93]
 [ 76253.86]
 [ 15505.73]
 [120542.52]
 [ 91992.39]
 [ 64664.71]
 [131876.9 ]
 [ 94657.16]
 [ 28754.33]
 [     0.  ]
 [162597.7 ]
 [ 93863.75]
 [ 44069.95]
 [ 77044.01]
 [134615.46]
 [ 67532.53]
 [ 28663.76]
 [ 78389.47]
 [ 86419.7 ]
 [123334.88]
 [ 38558.51]
 [  1315.46]
 [144372.41]
 [165349.2 ]
 [     0.  ]
 [ 22177.74]]


In [ ]:
print(X_test)

[[ 66051.52]
 [100671.96]
 [101913.08]
 [ 27892.92]
 [153441.51]
 [ 72107.6 ]
 [ 20229.59]
 [ 61136.38]
 [ 73994.56]
 [142107.34]
 [ 55493.95]
 [ 46014.02]
 [ 75328.87]]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
encoded = lab_enc.fit_transform(y_train)

# classifier = LogisticRegression(random_state = 0)
# classifier.fit(X_train, y_train)
#classifier.fit(X_train, y_train)
sc = preprocessing.StandardScaler().fit(X_train)
X_train = sc.transform(X_train)

y_train = np.array(y_train)

y_train = y_train.astype(int)
y_train

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[30,87000]])))

ValueError: ignored

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

## Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()